set -a

# Local setup
URL_KEYRING_NVIDIA_LOCAL=https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
VERSION_CUDA_LOCAL=12-8
VERSION_CUDNN_LOCAL=9-cuda-12
VERSION_PYTHON_LOCAL=3.12
VERSION_PIP_LOCAL=25.2
VERSION_SETUPTOOLS_LOCAL=80.9.0
VERSION_WHEEL_LOCAL=0.45.1

# Container setup
NAME_CONTAINER_PYTORCH_PROJECT=pytorch_project
VERSION_UBUNTU_CONTAINER=24.04
URL_KEYRING_NVIDIA_CONTAINER=https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2404/x86_64/cuda-keyring_1.1-1_all.deb
VERSION_CUDA_CONTAINER=12-8
VERSION_CUDNN_CONTAINER=9-cuda-12
VERSION_PYTHON_CONTAINER=3.12
VERSION_PIP_CONTAINER=25.2
VERSION_SETUPTOOLS_CONTAINER=80.9.0
VERSION_WHEEL_CONTAINER=0.45.1

set +a
